# Generated by Django 5.1.7 on 2025-03-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='img/default_user.jpg', upload_to='profile_photos')),
                ('about_me', models.TextField()),
                ('availability', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(max_length=254)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.designerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DesignerPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_samples')),
                ('designer_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_samples', to='users.designerpost')),
            ],
        ),
    ]
